### PR TITLE
allow installation with guzzle 7

### PR DESCRIPTION
**Pull request by dbu**
replace #19 and #21

(though i prefer #21 that drops the composer.lock file)

### CODE REVIEW

**Comment by pharman** [comment]
Thanks @dbu. As there is not much focus on this it's better to keep changes minimal.

**Comment by dbu** [comment]
thanks a lot!

**Comment by dbu** [comment]
@pharman i see that the packagist integration seems to not work: https://packagist.org/packages/sainsburys/guzzle-oauth2-plugin says "This package is not [auto-updated](https://packagist.org/about#how-to-update-packages)." - would be awesome if you can set that up so that the new tag becomes available for composer

**Comment by dbu** [comment]
when i am logged in, i can click the "update now" thing in packagist, now 3.0.7 is known on packagist / can be found by composer.

**Pull request merged**
