### PR TITLE
Update dependencies (Allow Guzzle 7)

### PR DESCRIPTION
**Pull request by ahfeel**

### CODE REVIEW

**Comment by havvg** [comment]
@rabbitlair, any chance getting this merged & tagged?

**Comment by rabbitlair** [comment]
@havvg, I have no permissions on this repository, but maybe @pharman can help with that. You would need to resolve merge conflicts first, though.

**Comment by havvg** [comment]
Oh, sorry, only saw you on the latest commit. Didn't double-check.

@ahfeel, you care to rebase your PR, so @pharman may easily merge it.

**Comment by pharman** [comment]
If you rebase we can merge this @ahfeel

**Comment by dbu** [comment]
@pharman  could we merge #21 instead?

**Pull request closed without merging**
