### PR TITLE
Improve tests and composer configuration

### PR DESCRIPTION
**Pull request by gregurco**
What I did:
- Remove composer.lock
- Increase version of phpunit from 4 to 5 (6 version is for php >= 7)
- Move bin to origin place
- Remove useless imports
- Remove deprecated setExpectedException
- Fix annotations
- Add tests
- Add php 7.1 in travis config

### CODE REVIEW

**Comment by gregurco** [comment]
@pharman any feedback?

**Comment by pharman** [comment]
Hi. Thanks for the contribution. Why have you removed composer.lock?

**Comment by gregurco** [comment]
@pharman first of all because it's not autonomous project, it's plugin. This lock file is not get into consideration when plugin is installed in projects. But contributors should work with fresh dependencies and not with these established in lock file. It's not good practice to keep lock file in plugins/bundles and libraries.

**Comment by pharman** [comment]
We want contributors to be working with the same set of dependencies during development just as with a regular app. I'm not sure removing it is really necessary.

**Comment by gregurco** [comment]
Why developers can not run `composer install` without composer.lock file? It's ok... you can check by yourself all top symfony bundles... no one has lock file. And what about next scenario:
1) you have lock with guzzle 6.1.1 in lock file
2) all developers will use this 6.1.1 and not the last
3) when user will run `composer require sainsburys/guzzle-oauth2-plugin` the latest version of guzzle will be installed... for example, it will be 6.2.2
4) you have no guarantee that plugin works with the latest version of guzzle and developers will discover that from issues created by users or if someone will update by himself, what I think happens rarely...

It's more safe and right to work with latest and different versions and not with lock... it's common practice. Of course I can revert this change, if I could not convince you.

**Comment by pharman** [comment]
I understand where your coming from. This project is not very actively maintained so having a lock file makes some sense. I suspect it's only here due to the original repo being forked. 

Composer is suitably vague on the issue: https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by p5vgregurco** [comment]
@pharman ok, for me it's not a problem. I pushed lock file.

**Comment by gregurco** [comment]
@pharman ok, for me it's not a problem. I pushed lock file.

**Comment by pharman** [comment]
Thanks for the contribution.

**Pull request merged**
